timezone: America/Los_Angeles
port: 3000
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
permalink: /blog/:year-:month-:day/:title
paginate_path: /blog/page-:num